name: juno_direct_checkout
description: SDK para criptografia e validação de dados do cartão de crédito para integração com a API de pagamentos da Juno/BoletoBancário.
version: 1.0.1
author:  Diefferson Santos <diefferson.sts@gmail.com>
homepage: https://github.com/tamojuno/juno_direct_checkout_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.juno.juno_direct_checkout
        pluginClass: JunoDirectCheckoutPlugin
      ios:
        pluginClass: JunoDirectCheckoutPlugin